
services:
  nativedubbointegration:
    image: nativedubbointegration
    build:
      context: .
      dockerfile: Tests/NativeDubboIntegration/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
